[package]
name = "config"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
regex = { workspace = true }
dirs = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
cron = { path = "../cron" }
security = { path = "../security" }
