CREATE TABLE runtime_audit_logs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    request_id VARCHAR(64) NULL COMMENT '与 hiveweb request-id 中间件对齐',
    session_id BIGINT NULL,
    agent_id BIGINT NULL,
    plugin_id BIGINT NULL,
    function_id BIGINT NULL,
    capability VARCHAR(64) NULL,
    event_type VARCHAR(32) NOT NULL COMMENT 'capability_call|capability_denied|plugin_invoke|workflow_node|agent_route|llm_invoke|llm_fallback',
    outcome VARCHAR(16) NOT NULL COMMENT 'success|error|denied|timeout',
    elapsed_ms INT NULL,
    error_message VARCHAR(512) NULL,
    payload_summary JSON NULL COMMENT '入参 / 出参摘要（脱敏后）',
    occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_ral_request (request_id),
    INDEX idx_ral_session (session_id),
    INDEX idx_ral_agent (agent_id),
    INDEX idx_ral_occurred_at (occurred_at DESC),
    INDEX idx_ral_capability (capability, outcome)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Runtime 审计日志（保留 ≥ 90 天）';
